#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the navbar)
name: "@satyaborg"

# Your site's title (e.g., Ben's Awesome Site, The GitHub Blog, etc.), used as part of the title tag like Home | Ben's Awesome Site.
title: Satya's blog

# Link to avatar in the navbar (/assets/images/avatar.png). Leave empty if no logo desired. Two avatars for light and dark mode.
# Avatar for light mode site
lightavatar: /assets/images/light_bauhaus_logo.png
# Avatar for dark mode site
darkavatar: /assets/images/dark_bauhaus_logo.png
# profile
mugshot: /assets/images/avatar.jpg
# resume
resume: /assets/documents/satya_borgohain_resume.pdf

# A short description (e.g., A blog dedicated to reviewing cat gifs), used as part of the title tag like Ben's Awesome Site | A blog dedicated to reviewing cat gifs instead of Ben's Awesome Site | Long description about a blog dedicated to reviewing cat gifs that would be used when page.title is not defined.
tagline: Thinking about thinking machines # Musings of a Polymorphic ape

# A longer description used for the description meta tag. Also used as fallback for pages that don't provide their own description, and also as part of the page's title tag if neither page.title nor site.tagline has been defined.
description: Thinking about thinking machines # Musings of a Polymorphic ape
masthead_desc: "Research Fellow at Monash University working on Machine Learning. When not thinking about thinking machines—probably hiking, reading, doodling, playing the guitar or occasionally, writing here."

# The full URL to your site. Note: site.github.url will be used by default.
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# global author information
author: satya-borgohain

# URL to a site-wide logo (e.g., /assets/your-company-logo.png)
logo: /assets/images/light_bauhaus_logo.png

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

permalink: posts/:title/ # /:year/:month/:day/:title/

# Includes an icon in the footer for each username you enter
footer-links:
  email: satya.borg@gmail.com
  facebook:
  github: satyaborg
  instagram: 
  linkedin: satyaborg
  rss: satyaborg # just type anything here for a working RSS icon
  twitter: satyaborg

collections:
  my_tags:
    output: true
    permalink: /tags/:slug/

defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: posts_by_tags

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed